# MySQL 성능 테스트
# 총 15600명 총 5분동안 요청
config:
  target: "http://localhost:8080"
  phases:
    # Phase 1: 초당 10명
    - duration: 60
      arrivalRate: 10

    # Phase 2: 초당 30명
    - duration: 60
      arrivalRate: 30

    # Phase 3: 초당 50명
    - duration: 60
      arrivalRate: 50

    # Phase 4: 초당 70명
    - duration: 60
      arrivalRate: 70

    # Phase 5: 초당 100명
    - duration: 60
      arrivalRate: 100
  processor: "./counter.js"

scenarios:
  - name: "대기열 성능 테스트"
    flow:
      - function: "generateUserId"
      # 1. 토큰 발급 테스트
      - post:
          url: "/concerts/tokens/{{ $randomNumber(1,1000) }}"
          capture:
            - json: "$.jwtToken"
              as: "authToken"
          expect:
            - statusCode: 200

      # 2. 대기열 상태 확인 (토큰 발급 성공한 경우만)
      - think: 2  # 2초 대기
      - get:
          url: "/concerts/tokens"
          headers:
            WaitingToken: "{{ authToken }}"
          expect:
            - statusCode: 200